### ISSUE TITLE
Version mismatch in Foundry and in the manifest download link

### ISSUE THREAD

**Issue by r-valyar** [maxstar/forbidden-lands-party-sheet#1]
As per the manifest file, the version of the module is 1.0.2, while when installed from the Add-On Module interface or using the manifest link, the product is 1.0.0 (using https://raw.githubusercontent.com/maxstar/forbidden-lands-party-sheet/master/module.json)

![flps_version](https://user-images.githubusercontent.com/63558984/90888128-548c6580-e3be-11ea-88c4-8a1aab40610d.jpg)

**Comment by maxstar** [comment]
Ah, yes. It seems I forgot to update the version field in module.json
Actually you have the latest version of the module, it's just the displayed version is wrong. I'll fix that in the next update.
Thanks for the report.
