### ISSUE TITLE
Sheet module not recognized by the updated system

### ISSUE THREAD

**Issue by superseva** [maxstar/forbidden-lands-party-sheet#4]
since "forbidden-lands" is now "forbidden-lands-rpg" the newly installed games can't utilize the module.

**Comment by maxstar** [comment]
I see that it's still called "forbidden-lands". Probably there was a temporary rename or something during the transfer to a different user. Please confirm that everything works with the latest system (https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt).
