### ISSUE TITLE
Czech lang

### ISSUE THREAD

**Issue by Mizy78** [maxstar/forbidden-lands-party-sheet#5]
May I offer you czech translate for sheet?

**Comment by maxstar** [comment]
Sure. Do you know how to work with git or you just have the translation file?

**Comment by Mizy78** [comment]
I have translated cs.json lang file. :)

Dne út 2. 3. 2021 15:15 uživatel maxstar <notifications@github.com> napsal:

**Comment by maxstar** [comment]
Attach it here and I'll add it to the module.

**Comment by Mizy78** [comment]
[cs.zip](https://github.com/maxstar/forbidden-lands-party-sheet/files/6070286/cs.zip)

I have one small problem. I need translate even the conection to journal, like hike, lead the way and other.

**Comment by maxstar** [comment]
Hm... I'll see what I can do with that.

**Comment by Mizy78** [comment]
Thx.  👍

**Comment by maxstar** [comment]
@Mizy78 
Please provide translations for these strings too (I'll make them translatable)
1. "Drag & drop characters here to add them to the party."
2. "Drag & drop characters to assign them to the desired travel activities."
3. "RESET"

In regards to journal entries: do I understand correctly that your journal entry names are in Czech?

**Comment by Mizy78** [comment]
1. "Přetáhni & pusť zde postavu, abys jí přidal do skupiny."
2. "Přetáhni & pusť zde postavu, abys jí přidělil k požadované cestovní aktivitě."
3. "RESETOVAT"


Many thanks

**Comment by maxstar** [comment]
In regards to journal entries: do I understand correctly that your journal entry names are in Czech?

**Comment by Mizy78** [comment]
And yes my journal entries are in Czech. :)

**Comment by maxstar** [comment]
@Mizy78 
1. Regarding journal entries. Linking to entries with localized names is not very simple and will impact performance every time you do anything on the party sheet, so I decided to not change anything. My only advice here - leave journal entry names in English, but have content localized.

2. I have found some more strings that weren't localized :)
    1. "Who rolls?"
    2. "Who pushes?"
    3. "Attention"
    4. "Please open your character sheet at least once before making travel rolls."
    
The first two appear when there are multiple characters assigned to an activity and GM makes a travel roll for that activity.

**Comment by Mizy78** [comment]
1. I understand and I am ok with your suggestion."

2. "Who rolls?" - "Kdo háže?"
    "Who pushes?" - "Kdo zkouší štěstí?"
    "Attention" - "Pozor"
    "Please open your character sheet at least once before making travel rolls." - "Před tím než provedete hod na cestování, otevřete prosím nejméně jednou list vaší postavy."

Thx :)

**Comment by maxstar** [comment]
@Mizy78 I have pushed the changes. Please update the module and check whether everything is as expected.

**Comment by Mizy78** [comment]
Everything seems to be ok.
Many many thanks.

**Comment by maxstar** [comment]
I've forgot to add your latest translations to version 1.0.4 (facepalm). Version 1.0.6 should have them :)
